# 开发环境特定配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: false
  use-management-port: false
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.easyarticle.controller